version: "3.9"

services:
  web:
    build: ./app                   # build do Dockerfile dentro da pasta app
    container_name: django_api
    env_file: 
      - .env                       # carrega variáveis do arquivo .env
    volumes:
      - ./app:/app                  # monta código local no container
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      DB_NAME: ${DB_NAME}           # pega do .env
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env                       # para manter senha/db consistentes
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
